-- noinspection SqlDialectInspectionForFile

-- A database for holding JSL output statistics
-- Created 3-22-2018
-- Author: M. Rossetti, rossetti@uark.edu
--
-- This design assumes that the model hierarchy cannot change during a simulation run
-- The model hierarchy could change between runs. This means that model elements
-- are associated with specific simulation runs (i.e. they are id dependent on simulation runs)

CREATE TABLE SIMULATION_RUN (
	ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	SIM_NAME VARCHAR(510) NOT NULL,
	MODEL_NAME VARCHAR(510) NOT NULL,
	EXP_NAME VARCHAR(510) NOT NULL,
	EXP_START_TIME_STAMP TIMESTAMP,
	EXP_END_TIME_STAMP TIMESTAMP,
	NUM_REPS INTEGER NOT NULL CHECK (NUM_REPS >=1),
	LAST_REP INTEGER, 
	LENGTH_OF_REP DOUBLE, 
	LENGTH_OF_WARM_UP DOUBLE,
	HAS_MORE_REPS BOOLEAN,
	REP_ALLOWED_EXEC_TIME BIGINT,
	REP_INIT_OPTION BOOLEAN,
	RESET_START_STREAM_OPTION BOOLEAN,
	ANTITHETIC_OPTION BOOLEAN,
	ADV_NEXT_SUB_STREAM_OPTION BOOLEAN,
	NUM_STREAM_ADVANCES INTEGER
);

CREATE TABLE MODEL_ELEMENT (
	SIM_RUN_ID_FK INTEGER NOT NULL,
	ELEMENT_NAME VARCHAR(510) NOT NULL,
	ELEMENT_ID BIGINT NOT NULL,
	CLASS_NAME VARCHAR(510) NOT NULL,
	PARENT_NAME_FK VARCHAR(510)
);

ALTER TABLE MODEL_ELEMENT
  ADD CONSTRAINT ME_PRIM_KY PRIMARY KEY (SIM_RUN_ID_FK, ELEMENT_NAME);
ALTER TABLE MODEL_ELEMENT
	ADD CONSTRAINT ME_SIMRUN_FK FOREIGN KEY (SIM_RUN_ID_FK) REFERENCES SIMULATION_RUN (ID);

CREATE TABLE WITHIN_REP_STAT (
	ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	MODEL_ELEMENT_NAME VARCHAR(510) NOT NULL,
	SIM_RUN_ID_FK INTEGER NOT NULL,
	STAT_NAME VARCHAR(510),
	REP_NUM INTEGER NOT NULL CHECK (REP_NUM >=1),
	STAT_COUNT DOUBLE CHECK (STAT_COUNT >=0),
	AVERAGE  DOUBLE,
	MINIMUM  DOUBLE,
	MAXIMUM  DOUBLE,
	WEIGHTED_SUM  DOUBLE,
	SUM_OF_WEIGHTS  DOUBLE,
	WEIGHTED_SSQ DOUBLE,
	LAST_VALUE DOUBLE,
	LAST_WEIGHT DOUBLE	
);

ALTER TABLE WITHIN_REP_STAT 
	ADD CONSTRAINT WRS_SIMRUN_FK FOREIGN KEY (SIM_RUN_ID_FK) REFERENCES SIMULATION_RUN (ID);
ALTER TABLE WITHIN_REP_STAT
  ADD CONSTRAINT WRS_UNIQUE_ELEMENT_SIMRUN_REPNUM UNIQUE (MODEL_ELEMENT_NAME, SIM_RUN_ID_FK, REP_NUM);
ALTER TABLE WITHIN_REP_STAT
  ADD CONSTRAINT WRS_MODEL_ELEMENT_FK FOREIGN KEY (SIM_RUN_ID_FK, MODEL_ELEMENT_NAME) REFERENCES MODEL_ELEMENT (SIM_RUN_ID_FK, ELEMENT_NAME);

CREATE TABLE ACROSS_REP_STAT (
	ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	MODEL_ELEMENT_NAME VARCHAR(510) NOT NULL,
	SIM_RUN_ID_FK INTEGER NOT NULL,
	STAT_NAME VARCHAR(510),
	STAT_COUNT DOUBLE CHECK (STAT_COUNT >=0),
	AVERAGE  DOUBLE,
	STD_DEV DOUBLE,
	STD_ERR DOUBLE,
	HALF_WIDTH DOUBLE,
	CONF_LEVEL DOUBLE,
	MINIMUM  DOUBLE,
	MAXIMUM  DOUBLE,
	WEIGHTED_SUM  DOUBLE,
	SUM_OF_WEIGHTS  DOUBLE,
	WEIGHTED_SSQ DOUBLE,
	DEV_SSQ DOUBLE,
	LAST_VALUE DOUBLE,
	LAST_WEIGHT DOUBLE,
	KURTOSIS DOUBLE,
	SKEWNESS DOUBLE,
	LAG1_COV DOUBLE,
	LAG1_CORR DOUBLE,
	VON_NEUMAN_LAG1_STAT DOUBLE,
	NUM_MISSING_OBS DOUBLE
);

ALTER TABLE ACROSS_REP_STAT 
	ADD CONSTRAINT ARS_SIMRUN_FK FOREIGN KEY (SIM_RUN_ID_FK) REFERENCES SIMULATION_RUN (ID);

ALTER TABLE ACROSS_REP_STAT
  ADD CONSTRAINT ARS_MODEL_ELEMENT_FK FOREIGN KEY (SIM_RUN_ID_FK, MODEL_ELEMENT_NAME) REFERENCES MODEL_ELEMENT (SIM_RUN_ID_FK, ELEMENT_NAME);

CREATE TABLE WITHIN_REP_COUNTER_STAT (
	ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	MODEL_ELEMENT_NAME VARCHAR(510) NOT NULL,
	SIM_RUN_ID_FK INTEGER NOT NULL,
	STAT_NAME VARCHAR(510),
	REP_NUM INTEGER NOT NULL CHECK (REP_NUM >=1),
	LAST_VALUE DOUBLE	
);

ALTER TABLE WITHIN_REP_COUNTER_STAT 
	ADD CONSTRAINT WRCS_SIMRUN_FK FOREIGN KEY (SIM_RUN_ID_FK) REFERENCES SIMULATION_RUN (ID);

ALTER TABLE WITHIN_REP_COUNTER_STAT
  ADD CONSTRAINT WRCS_UNIQUE_ELEMENT_SIMRUN_REPNUM UNIQUE (MODEL_ELEMENT_NAME, SIM_RUN_ID_FK, REP_NUM);

ALTER TABLE WITHIN_REP_COUNTER_STAT
  ADD CONSTRAINT WRCS_MODEL_ELEMENT_FK FOREIGN KEY (SIM_RUN_ID_FK, MODEL_ELEMENT_NAME) REFERENCES MODEL_ELEMENT (SIM_RUN_ID_FK, ELEMENT_NAME);

CREATE TABLE BATCH_STAT (
	ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	MODEL_ELEMENT_NAME VARCHAR(510) NOT NULL,
	SIM_RUN_ID_FK INTEGER NOT NULL,
	STAT_NAME VARCHAR(510),
	REP_NUM INTEGER NOT NULL CHECK (REP_NUM >=1),
	STAT_COUNT DOUBLE CHECK (STAT_COUNT >=0),
	AVERAGE  DOUBLE,
	STD_DEV DOUBLE,
	STD_ERR DOUBLE,
	HALF_WIDTH DOUBLE,
	CONF_LEVEL DOUBLE,
	MINIMUM  DOUBLE,
	MAXIMUM  DOUBLE,
	WEIGHTED_SUM  DOUBLE,
	SUM_OF_WEIGHTS  DOUBLE,
	WEIGHTED_SSQ DOUBLE,
	DEV_SSQ DOUBLE,
	LAST_VALUE DOUBLE,
	LAST_WEIGHT DOUBLE,
	KURTOSIS DOUBLE,
	SKEWNESS DOUBLE,
	LAG1_COV DOUBLE,
	LAG1_CORR DOUBLE,
	VON_NEUMAN_LAG1_STAT DOUBLE,
	NUM_MISSING_OBS DOUBLE,
	MIN_BATCH_SIZE DOUBLE,
	MIN_NUM_BATCHES DOUBLE,
	MAX_NUM_BATCHES_MULTIPLE DOUBLE,
	MAX_NUM_BATCHES DOUBLE,
	NUM_REBATCHES DOUBLE,
	CURRENT_BATCH_SIZE DOUBLE,
	AMT_UNBATCHED DOUBLE,
	TOTAL_NUM_OBS DOUBLE
);

ALTER TABLE BATCH_STAT
	ADD CONSTRAINT BS_SIMRUN_FK FOREIGN KEY (SIM_RUN_ID_FK) REFERENCES SIMULATION_RUN (ID);

ALTER TABLE BATCH_STAT
  ADD CONSTRAINT BS_MODEL_ELEMENT_FK FOREIGN KEY (SIM_RUN_ID_FK, MODEL_ELEMENT_NAME) REFERENCES MODEL_ELEMENT (SIM_RUN_ID_FK, ELEMENT_NAME);
