/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.JslDb;
import jsl.utilities.jsldbsrc.tables.records.AcrossRepViewRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AcrossRepView extends TableImpl<AcrossRepViewRecord> {

    private static final long serialVersionUID = 1963431712;

    /**
     * The reference instance of <code>JSL_DB.ACROSS_REP_VIEW</code>
     */
    public static final AcrossRepView ACROSS_REP_VIEW = new AcrossRepView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AcrossRepViewRecord> getRecordType() {
        return AcrossRepViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.ACROSS_REP_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<AcrossRepViewRecord, Integer> SIM_RUN_ID_FK = createField("SIM_RUN_ID_FK", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.ACROSS_REP_VIEW.EXP_NAME</code>.
     */
    public final TableField<AcrossRepViewRecord, String> EXP_NAME = createField("EXP_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.ACROSS_REP_VIEW.ELEMENT_NAME</code>.
     */
    public final TableField<AcrossRepViewRecord, String> ELEMENT_NAME = createField("ELEMENT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.ACROSS_REP_VIEW.STAT_NAME</code>.
     */
    public final TableField<AcrossRepViewRecord, String> STAT_NAME = createField("STAT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.ACROSS_REP_VIEW.STAT_COUNT</code>.
     */
    public final TableField<AcrossRepViewRecord, Double> STAT_COUNT = createField("STAT_COUNT", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.ACROSS_REP_VIEW.AVERAGE</code>.
     */
    public final TableField<AcrossRepViewRecord, Double> AVERAGE = createField("AVERAGE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.ACROSS_REP_VIEW.STD_DEV</code>.
     */
    public final TableField<AcrossRepViewRecord, Double> STD_DEV = createField("STD_DEV", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>JSL_DB.ACROSS_REP_VIEW</code> table reference
     */
    public AcrossRepView() {
        this(DSL.name("ACROSS_REP_VIEW"), null);
    }

    /**
     * Create an aliased <code>JSL_DB.ACROSS_REP_VIEW</code> table reference
     */
    public AcrossRepView(String alias) {
        this(DSL.name(alias), ACROSS_REP_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.ACROSS_REP_VIEW</code> table reference
     */
    public AcrossRepView(Name alias) {
        this(alias, ACROSS_REP_VIEW);
    }

    private AcrossRepView(Name alias, Table<AcrossRepViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private AcrossRepView(Name alias, Table<AcrossRepViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepView as(String alias) {
        return new AcrossRepView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepView as(Name alias) {
        return new AcrossRepView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AcrossRepView rename(String name) {
        return new AcrossRepView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AcrossRepView rename(Name name) {
        return new AcrossRepView(name, null);
    }
}
