/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.JslDb;
import jsl.utilities.jsldbsrc.tables.records.BatchStatViewRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchStatView extends TableImpl<BatchStatViewRecord> {

    private static final long serialVersionUID = -816362892;

    /**
     * The reference instance of <code>JSL_DB.BATCH_STAT_VIEW</code>
     */
    public static final BatchStatView BATCH_STAT_VIEW = new BatchStatView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchStatViewRecord> getRecordType() {
        return BatchStatViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<BatchStatViewRecord, Integer> SIM_RUN_ID_FK = createField("SIM_RUN_ID_FK", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.EXP_NAME</code>.
     */
    public final TableField<BatchStatViewRecord, String> EXP_NAME = createField("EXP_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.ELEMENT_NAME</code>.
     */
    public final TableField<BatchStatViewRecord, String> ELEMENT_NAME = createField("ELEMENT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.STAT_NAME</code>.
     */
    public final TableField<BatchStatViewRecord, String> STAT_NAME = createField("STAT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.STAT_COUNT</code>.
     */
    public final TableField<BatchStatViewRecord, Double> STAT_COUNT = createField("STAT_COUNT", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.AVERAGE</code>.
     */
    public final TableField<BatchStatViewRecord, Double> AVERAGE = createField("AVERAGE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.STD_DEV</code>.
     */
    public final TableField<BatchStatViewRecord, Double> STD_DEV = createField("STD_DEV", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>JSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    public BatchStatView() {
        this(DSL.name("BATCH_STAT_VIEW"), null);
    }

    /**
     * Create an aliased <code>JSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    public BatchStatView(String alias) {
        this(DSL.name(alias), BATCH_STAT_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    public BatchStatView(Name alias) {
        this(alias, BATCH_STAT_VIEW);
    }

    private BatchStatView(Name alias, Table<BatchStatViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchStatView(Name alias, Table<BatchStatViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchStatView as(String alias) {
        return new BatchStatView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchStatView as(Name alias) {
        return new BatchStatView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchStatView rename(String name) {
        return new BatchStatView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchStatView rename(Name name) {
        return new BatchStatView(name, null);
    }
}
