/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.JslDb;
import jsl.utilities.jsldbsrc.tables.records.PwDiffWithinRepViewRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PwDiffWithinRepView extends TableImpl<PwDiffWithinRepViewRecord> {

    private static final long serialVersionUID = 1421979722;

    /**
     * The reference instance of <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW</code>
     */
    public static final PwDiffWithinRepView PW_DIFF_WITHIN_REP_VIEW = new PwDiffWithinRepView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PwDiffWithinRepViewRecord> getRecordType() {
        return PwDiffWithinRepViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.SIM_NAME</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, String> SIM_NAME = createField("SIM_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_SIM_NUM</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, Integer> A_SIM_NUM = createField("A_SIM_NUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, String> STAT_NAME = createField("STAT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_EXP_NAME</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, String> A_EXP_NAME = createField("A_EXP_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.REP_NUM</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, Integer> REP_NUM = createField("REP_NUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_VALUE</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, Double> A_VALUE = createField("A_VALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_SIM_NUM</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, Integer> B_SIM_NUM = createField("B_SIM_NUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_EXP_NAME</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, String> B_EXP_NAME = createField("B_EXP_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_VALUE</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, Double> B_VALUE = createField("B_VALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.DIFF_NAME</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, String> DIFF_NAME = createField("DIFF_NAME", org.jooq.impl.SQLDataType.VARCHAR(1025).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_MINUS_B</code>.
     */
    public final TableField<PwDiffWithinRepViewRecord, Double> A_MINUS_B = createField("A_MINUS_B", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW</code> table reference
     */
    public PwDiffWithinRepView() {
        this(DSL.name("PW_DIFF_WITHIN_REP_VIEW"), null);
    }

    /**
     * Create an aliased <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW</code> table reference
     */
    public PwDiffWithinRepView(String alias) {
        this(DSL.name(alias), PW_DIFF_WITHIN_REP_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW</code> table reference
     */
    public PwDiffWithinRepView(Name alias) {
        this(alias, PW_DIFF_WITHIN_REP_VIEW);
    }

    private PwDiffWithinRepView(Name alias, Table<PwDiffWithinRepViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private PwDiffWithinRepView(Name alias, Table<PwDiffWithinRepViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PwDiffWithinRepView as(String alias) {
        return new PwDiffWithinRepView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PwDiffWithinRepView as(Name alias) {
        return new PwDiffWithinRepView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PwDiffWithinRepView rename(String name) {
        return new PwDiffWithinRepView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PwDiffWithinRepView rename(Name name) {
        return new PwDiffWithinRepView(name, null);
    }
}
