/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.JslDb;
import jsl.utilities.jsldbsrc.Keys;
import jsl.utilities.jsldbsrc.tables.records.WithinRepCounterStatRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepCounterStat extends TableImpl<WithinRepCounterStatRecord> {

    private static final long serialVersionUID = 1871745645;

    /**
     * The reference instance of <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code>
     */
    public static final WithinRepCounterStat WITHIN_REP_COUNTER_STAT = new WithinRepCounterStat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithinRepCounterStatRecord> getRecordType() {
        return WithinRepCounterStatRecord.class;
    }

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.ID</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.MODEL_ELEMENT_NAME</code>.
     */
    public final TableField<WithinRepCounterStatRecord, String> MODEL_ELEMENT_NAME = createField("MODEL_ELEMENT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Integer> SIM_RUN_ID_FK = createField("SIM_RUN_ID_FK", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.STAT_NAME</code>.
     */
    public final TableField<WithinRepCounterStatRecord, String> STAT_NAME = createField("STAT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.REP_NUM</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Integer> REP_NUM = createField("REP_NUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.LAST_VALUE</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Double> LAST_VALUE = createField("LAST_VALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code> table reference
     */
    public WithinRepCounterStat() {
        this(DSL.name("WITHIN_REP_COUNTER_STAT"), null);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code> table reference
     */
    public WithinRepCounterStat(String alias) {
        this(DSL.name(alias), WITHIN_REP_COUNTER_STAT);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code> table reference
     */
    public WithinRepCounterStat(Name alias) {
        this(alias, WITHIN_REP_COUNTER_STAT);
    }

    private WithinRepCounterStat(Name alias, Table<WithinRepCounterStatRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithinRepCounterStat(Name alias, Table<WithinRepCounterStatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WithinRepCounterStatRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WITHIN_REP_COUNTER_STAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WithinRepCounterStatRecord> getPrimaryKey() {
        return Keys.SQL180629175107690;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WithinRepCounterStatRecord>> getKeys() {
        return Arrays.<UniqueKey<WithinRepCounterStatRecord>>asList(Keys.SQL180629175107690, Keys.WRCS_UNIQUE_ELEMENT_SIMRUN_REPNUM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WithinRepCounterStatRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WithinRepCounterStatRecord, ?>>asList(Keys.WRCS_MODEL_ELEMENT_FK, Keys.WRCS_SIMRUN_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepCounterStat as(String alias) {
        return new WithinRepCounterStat(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepCounterStat as(Name alias) {
        return new WithinRepCounterStat(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterStat rename(String name) {
        return new WithinRepCounterStat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterStat rename(Name name) {
        return new WithinRepCounterStat(name, null);
    }
}
