/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.JslDb;
import jsl.utilities.jsldbsrc.tables.records.WithinRepResponseViewRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepResponseView extends TableImpl<WithinRepResponseViewRecord> {

    private static final long serialVersionUID = 1094954419;

    /**
     * The reference instance of <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW</code>
     */
    public static final WithinRepResponseView WITHIN_REP_RESPONSE_VIEW = new WithinRepResponseView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithinRepResponseViewRecord> getRecordType() {
        return WithinRepResponseViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<WithinRepResponseViewRecord, Integer> SIM_RUN_ID_FK = createField("SIM_RUN_ID_FK", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.EXP_NAME</code>.
     */
    public final TableField<WithinRepResponseViewRecord, String> EXP_NAME = createField("EXP_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.STAT_NAME</code>.
     */
    public final TableField<WithinRepResponseViewRecord, String> STAT_NAME = createField("STAT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.REP_NUM</code>.
     */
    public final TableField<WithinRepResponseViewRecord, Integer> REP_NUM = createField("REP_NUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.AVERAGE</code>.
     */
    public final TableField<WithinRepResponseViewRecord, Double> AVERAGE = createField("AVERAGE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW</code> table reference
     */
    public WithinRepResponseView() {
        this(DSL.name("WITHIN_REP_RESPONSE_VIEW"), null);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW</code> table reference
     */
    public WithinRepResponseView(String alias) {
        this(DSL.name(alias), WITHIN_REP_RESPONSE_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW</code> table reference
     */
    public WithinRepResponseView(Name alias) {
        this(alias, WITHIN_REP_RESPONSE_VIEW);
    }

    private WithinRepResponseView(Name alias, Table<WithinRepResponseViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithinRepResponseView(Name alias, Table<WithinRepResponseViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseView as(String alias) {
        return new WithinRepResponseView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseView as(Name alias) {
        return new WithinRepResponseView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepResponseView rename(String name) {
        return new WithinRepResponseView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepResponseView rename(Name name) {
        return new WithinRepResponseView(name, null);
    }
}
