/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.JslDb;
import jsl.utilities.jsldbsrc.tables.records.WithinRepViewRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepView extends TableImpl<WithinRepViewRecord> {

    private static final long serialVersionUID = 949060304;

    /**
     * The reference instance of <code>JSL_DB.WITHIN_REP_VIEW</code>
     */
    public static final WithinRepView WITHIN_REP_VIEW = new WithinRepView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithinRepViewRecord> getRecordType() {
        return WithinRepViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<WithinRepViewRecord, Integer> SIM_RUN_ID_FK = createField("SIM_RUN_ID_FK", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.EXP_NAME</code>.
     */
    public final TableField<WithinRepViewRecord, String> EXP_NAME = createField("EXP_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    public final TableField<WithinRepViewRecord, String> STAT_NAME = createField("STAT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.REP_NUM</code>.
     */
    public final TableField<WithinRepViewRecord, Integer> REP_NUM = createField("REP_NUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.VALUE</code>.
     */
    public final TableField<WithinRepViewRecord, Double> VALUE = createField("VALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>JSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    public WithinRepView() {
        this(DSL.name("WITHIN_REP_VIEW"), null);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    public WithinRepView(String alias) {
        this(DSL.name(alias), WITHIN_REP_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    public WithinRepView(Name alias) {
        this(alias, WITHIN_REP_VIEW);
    }

    private WithinRepView(Name alias, Table<WithinRepViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithinRepView(Name alias, Table<WithinRepViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepView as(String alias) {
        return new WithinRepView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepView as(Name alias) {
        return new WithinRepView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepView rename(String name) {
        return new WithinRepView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepView rename(Name name) {
        return new WithinRepView(name, null);
    }
}
