/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.JslDb;
import jsl.utilities.jsldbsrc.tables.records.WithinRepCounterViewRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepCounterView extends TableImpl<WithinRepCounterViewRecord> {

    private static final long serialVersionUID = 388091840;

    /**
     * The reference instance of <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code>
     */
    public static final WithinRepCounterView WITHIN_REP_COUNTER_VIEW = new WithinRepCounterView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithinRepCounterViewRecord> getRecordType() {
        return WithinRepCounterViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<WithinRepCounterViewRecord, Integer> SIM_RUN_ID_FK = createField("SIM_RUN_ID_FK", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.EXP_NAME</code>.
     */
    public final TableField<WithinRepCounterViewRecord, String> EXP_NAME = createField("EXP_NAME", org.jooq.impl.SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.STAT_NAME</code>.
     */
    public final TableField<WithinRepCounterViewRecord, String> STAT_NAME = createField("STAT_NAME", org.jooq.impl.SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.REP_NUM</code>.
     */
    public final TableField<WithinRepCounterViewRecord, Integer> REP_NUM = createField("REP_NUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.LAST_VALUE</code>.
     */
    public final TableField<WithinRepCounterViewRecord, Double> LAST_VALUE = createField("LAST_VALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code> table reference
     */
    public WithinRepCounterView() {
        this(DSL.name("WITHIN_REP_COUNTER_VIEW"), null);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code> table reference
     */
    public WithinRepCounterView(String alias) {
        this(DSL.name(alias), WITHIN_REP_COUNTER_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code> table reference
     */
    public WithinRepCounterView(Name alias) {
        this(alias, WITHIN_REP_COUNTER_VIEW);
    }

    private WithinRepCounterView(Name alias, Table<WithinRepCounterViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithinRepCounterView(Name alias, Table<WithinRepCounterViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepCounterView as(String alias) {
        return new WithinRepCounterView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepCounterView as(Name alias) {
        return new WithinRepCounterView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterView rename(String name) {
        return new WithinRepCounterView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterView rename(Name name) {
        return new WithinRepCounterView(name, null);
    }
}
