/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables.records;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.tables.AcrossRepView;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AcrossRepViewRecord extends TableRecordImpl<AcrossRepViewRecord> implements Record7<Integer, String, String, String, Double, Double, Double> {

    private static final long serialVersionUID = -1527578784;

    /**
     * Setter for <code>JSL_DB.ACROSS_REP_VIEW.SIM_RUN_ID_FK</code>.
     */
    public void setSimRunIdFk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>JSL_DB.ACROSS_REP_VIEW.SIM_RUN_ID_FK</code>.
     */
    public Integer getSimRunIdFk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>JSL_DB.ACROSS_REP_VIEW.EXP_NAME</code>.
     */
    public void setExpName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>JSL_DB.ACROSS_REP_VIEW.EXP_NAME</code>.
     */
    public String getExpName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>JSL_DB.ACROSS_REP_VIEW.ELEMENT_NAME</code>.
     */
    public void setElementName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>JSL_DB.ACROSS_REP_VIEW.ELEMENT_NAME</code>.
     */
    public String getElementName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>JSL_DB.ACROSS_REP_VIEW.STAT_NAME</code>.
     */
    public void setStatName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>JSL_DB.ACROSS_REP_VIEW.STAT_NAME</code>.
     */
    public String getStatName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>JSL_DB.ACROSS_REP_VIEW.STAT_COUNT</code>.
     */
    public void setStatCount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>JSL_DB.ACROSS_REP_VIEW.STAT_COUNT</code>.
     */
    public Double getStatCount() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>JSL_DB.ACROSS_REP_VIEW.AVERAGE</code>.
     */
    public void setAverage(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>JSL_DB.ACROSS_REP_VIEW.AVERAGE</code>.
     */
    public Double getAverage() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>JSL_DB.ACROSS_REP_VIEW.STD_DEV</code>.
     */
    public void setStdDev(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>JSL_DB.ACROSS_REP_VIEW.STD_DEV</code>.
     */
    public Double getStdDev() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Double, Double, Double> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Double, Double, Double> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AcrossRepView.ACROSS_REP_VIEW.SIM_RUN_ID_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AcrossRepView.ACROSS_REP_VIEW.EXP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AcrossRepView.ACROSS_REP_VIEW.ELEMENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AcrossRepView.ACROSS_REP_VIEW.STAT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return AcrossRepView.ACROSS_REP_VIEW.STAT_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return AcrossRepView.ACROSS_REP_VIEW.AVERAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return AcrossRepView.ACROSS_REP_VIEW.STD_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getStatCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getAverage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getStdDev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getStatCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getAverage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getStdDev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord value1(Integer value) {
        setSimRunIdFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord value2(String value) {
        setExpName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord value3(String value) {
        setElementName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord value4(String value) {
        setStatName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord value5(Double value) {
        setStatCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord value6(Double value) {
        setAverage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord value7(Double value) {
        setStdDev(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AcrossRepViewRecord values(Integer value1, String value2, String value3, String value4, Double value5, Double value6, Double value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AcrossRepViewRecord
     */
    public AcrossRepViewRecord() {
        super(AcrossRepView.ACROSS_REP_VIEW);
    }

    /**
     * Create a detached, initialised AcrossRepViewRecord
     */
    public AcrossRepViewRecord(Integer simRunIdFk, String expName, String elementName, String statName, Double statCount, Double average, Double stdDev) {
        super(AcrossRepView.ACROSS_REP_VIEW);

        set(0, simRunIdFk);
        set(1, expName);
        set(2, elementName);
        set(3, statName);
        set(4, statCount);
        set(5, average);
        set(6, stdDev);
    }
}
