/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables.records;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.tables.ModelElement;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelElementRecord extends UpdatableRecordImpl<ModelElementRecord> implements Record7<Integer, String, Long, String, String, Integer, Integer> {

    private static final long serialVersionUID = 47225104;

    /**
     * Setter for <code>JSL_DB.MODEL_ELEMENT.SIM_RUN_ID_FK</code>.
     */
    public void setSimRunIdFk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>JSL_DB.MODEL_ELEMENT.SIM_RUN_ID_FK</code>.
     */
    public Integer getSimRunIdFk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>JSL_DB.MODEL_ELEMENT.ELEMENT_NAME</code>.
     */
    public void setElementName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>JSL_DB.MODEL_ELEMENT.ELEMENT_NAME</code>.
     */
    public String getElementName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>JSL_DB.MODEL_ELEMENT.ELEMENT_ID</code>.
     */
    public void setElementId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>JSL_DB.MODEL_ELEMENT.ELEMENT_ID</code>.
     */
    public Long getElementId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>JSL_DB.MODEL_ELEMENT.CLASS_NAME</code>.
     */
    public void setClassName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>JSL_DB.MODEL_ELEMENT.CLASS_NAME</code>.
     */
    public String getClassName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>JSL_DB.MODEL_ELEMENT.PARENT_NAME_FK</code>.
     */
    public void setParentNameFk(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>JSL_DB.MODEL_ELEMENT.PARENT_NAME_FK</code>.
     */
    public String getParentNameFk() {
        return (String) get(4);
    }

    /**
     * Setter for <code>JSL_DB.MODEL_ELEMENT.LEFT_COUNT</code>.
     */
    public void setLeftCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>JSL_DB.MODEL_ELEMENT.LEFT_COUNT</code>.
     */
    public Integer getLeftCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>JSL_DB.MODEL_ELEMENT.RIGHT_COUNT</code>.
     */
    public void setRightCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>JSL_DB.MODEL_ELEMENT.RIGHT_COUNT</code>.
     */
    public Integer getRightCount() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Long, String, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Long, String, String, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ModelElement.MODEL_ELEMENT.ELEMENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ModelElement.MODEL_ELEMENT.ELEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ModelElement.MODEL_ELEMENT.CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ModelElement.MODEL_ELEMENT.PARENT_NAME_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ModelElement.MODEL_ELEMENT.LEFT_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ModelElement.MODEL_ELEMENT.RIGHT_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getElementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getParentNameFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getLeftCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getRightCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getElementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getParentNameFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLeftCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getRightCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord value1(Integer value) {
        setSimRunIdFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord value2(String value) {
        setElementName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord value3(Long value) {
        setElementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord value4(String value) {
        setClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord value5(String value) {
        setParentNameFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord value6(Integer value) {
        setLeftCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord value7(Integer value) {
        setRightCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelElementRecord values(Integer value1, String value2, Long value3, String value4, String value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelElementRecord
     */
    public ModelElementRecord() {
        super(ModelElement.MODEL_ELEMENT);
    }

    /**
     * Create a detached, initialised ModelElementRecord
     */
    public ModelElementRecord(Integer simRunIdFk, String elementName, Long elementId, String className, String parentNameFk, Integer leftCount, Integer rightCount) {
        super(ModelElement.MODEL_ELEMENT);

        set(0, simRunIdFk);
        set(1, elementName);
        set(2, elementId);
        set(3, className);
        set(4, parentNameFk);
        set(5, leftCount);
        set(6, rightCount);
    }
}
