/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables.records;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.tables.WithinRepResponseView;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepResponseViewRecord extends TableRecordImpl<WithinRepResponseViewRecord> implements Record5<Integer, String, String, Integer, Double> {

    private static final long serialVersionUID = 701576290;

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.SIM_RUN_ID_FK</code>.
     */
    public void setSimRunIdFk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.SIM_RUN_ID_FK</code>.
     */
    public Integer getSimRunIdFk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.EXP_NAME</code>.
     */
    public void setExpName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.EXP_NAME</code>.
     */
    public String getExpName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.STAT_NAME</code>.
     */
    public void setStatName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.STAT_NAME</code>.
     */
    public String getStatName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.REP_NUM</code>.
     */
    public void setRepNum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.REP_NUM</code>.
     */
    public Integer getRepNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.AVERAGE</code>.
     */
    public void setAverage(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW.AVERAGE</code>.
     */
    public Double getAverage() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.SIM_RUN_ID_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.EXP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.STAT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.REP_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW.AVERAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getStatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getRepNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getAverage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRepNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getAverage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseViewRecord value1(Integer value) {
        setSimRunIdFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseViewRecord value2(String value) {
        setExpName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseViewRecord value3(String value) {
        setStatName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseViewRecord value4(Integer value) {
        setRepNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseViewRecord value5(Double value) {
        setAverage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepResponseViewRecord values(Integer value1, String value2, String value3, Integer value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WithinRepResponseViewRecord
     */
    public WithinRepResponseViewRecord() {
        super(WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW);
    }

    /**
     * Create a detached, initialised WithinRepResponseViewRecord
     */
    public WithinRepResponseViewRecord(Integer simRunIdFk, String expName, String statName, Integer repNum, Double average) {
        super(WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW);

        set(0, simRunIdFk);
        set(1, expName);
        set(2, statName);
        set(3, repNum);
        set(4, average);
    }
}
