/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc.tables.records;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.tables.WithinRepView;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepViewRecord extends TableRecordImpl<WithinRepViewRecord> implements Record6<Integer, String, String, String, Integer, Double> {

    private static final long serialVersionUID = 1621761533;

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_VIEW.SIM_RUN_ID_FK</code>.
     */
    public void setSimRunIdFk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_VIEW.SIM_RUN_ID_FK</code>.
     */
    public Integer getSimRunIdFk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_VIEW.EXP_NAME</code>.
     */
    public void setExpName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_VIEW.EXP_NAME</code>.
     */
    public String getExpName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_VIEW.ELEMENT_NAME</code>.
     */
    public void setElementName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_VIEW.ELEMENT_NAME</code>.
     */
    public String getElementName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    public void setStatName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    public String getStatName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_VIEW.REP_NUM</code>.
     */
    public void setRepNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_VIEW.REP_NUM</code>.
     */
    public Integer getRepNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>JSL_DB.WITHIN_REP_VIEW.VALUE</code>.
     */
    public void setValue(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>JSL_DB.WITHIN_REP_VIEW.VALUE</code>.
     */
    public Double getValue() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WithinRepView.WITHIN_REP_VIEW.SIM_RUN_ID_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WithinRepView.WITHIN_REP_VIEW.EXP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WithinRepView.WITHIN_REP_VIEW.ELEMENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WithinRepView.WITHIN_REP_VIEW.STAT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return WithinRepView.WITHIN_REP_VIEW.REP_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return WithinRepView.WITHIN_REP_VIEW.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getRepNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSimRunIdFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getElementName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRepNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepViewRecord value1(Integer value) {
        setSimRunIdFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepViewRecord value2(String value) {
        setExpName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepViewRecord value3(String value) {
        setElementName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepViewRecord value4(String value) {
        setStatName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepViewRecord value5(Integer value) {
        setRepNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepViewRecord value6(Double value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithinRepViewRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WithinRepViewRecord
     */
    public WithinRepViewRecord() {
        super(WithinRepView.WITHIN_REP_VIEW);
    }

    /**
     * Create a detached, initialised WithinRepViewRecord
     */
    public WithinRepViewRecord(Integer simRunIdFk, String expName, String elementName, String statName, Integer repNum, Double value) {
        super(WithinRepView.WITHIN_REP_VIEW);

        set(0, simRunIdFk);
        set(1, expName);
        set(2, elementName);
        set(3, statName);
        set(4, repNum);
        set(5, value);
    }
}
