/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.tables.AcrossRepStat;
import jsl.utilities.jsldbsrc.tables.BatchStat;
import jsl.utilities.jsldbsrc.tables.ModelElement;
import jsl.utilities.jsldbsrc.tables.SimulationRun;
import jsl.utilities.jsldbsrc.tables.WithinRepCounterStat;
import jsl.utilities.jsldbsrc.tables.WithinRepStat;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JslDb extends SchemaImpl {

    private static final long serialVersionUID = 1607742101;

    /**
     * The reference instance of <code>JSL_DB</code>
     */
    public static final JslDb JSL_DB = new JslDb();

    /**
     * The table <code>JSL_DB.ACROSS_REP_STAT</code>.
     */
    public final AcrossRepStat ACROSS_REP_STAT = jsl.utilities.jsldbsrc.tables.AcrossRepStat.ACROSS_REP_STAT;

    /**
     * The table <code>JSL_DB.BATCH_STAT</code>.
     */
    public final BatchStat BATCH_STAT = jsl.utilities.jsldbsrc.tables.BatchStat.BATCH_STAT;

    /**
     * The table <code>JSL_DB.MODEL_ELEMENT</code>.
     */
    public final ModelElement MODEL_ELEMENT = jsl.utilities.jsldbsrc.tables.ModelElement.MODEL_ELEMENT;

    /**
     * The table <code>JSL_DB.SIMULATION_RUN</code>.
     */
    public final SimulationRun SIMULATION_RUN = jsl.utilities.jsldbsrc.tables.SimulationRun.SIMULATION_RUN;

    /**
     * The table <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code>.
     */
    public final WithinRepCounterStat WITHIN_REP_COUNTER_STAT = jsl.utilities.jsldbsrc.tables.WithinRepCounterStat.WITHIN_REP_COUNTER_STAT;

    /**
     * The table <code>JSL_DB.WITHIN_REP_STAT</code>.
     */
    public final WithinRepStat WITHIN_REP_STAT = jsl.utilities.jsldbsrc.tables.WithinRepStat.WITHIN_REP_STAT;

    /**
     * No further instances allowed
     */
    private JslDb() {
        super("JSL_DB", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AcrossRepStat.ACROSS_REP_STAT,
            BatchStat.BATCH_STAT,
            ModelElement.MODEL_ELEMENT,
            SimulationRun.SIMULATION_RUN,
            WithinRepCounterStat.WITHIN_REP_COUNTER_STAT,
            WithinRepStat.WITHIN_REP_STAT);
    }
}
