/*
 * This file is generated by jOOQ.
*/
package jsl.utilities.jsldbsrc;


import javax.annotation.Generated;

import jsl.utilities.jsldbsrc.tables.AcrossRepStat;
import jsl.utilities.jsldbsrc.tables.AcrossRepView;
import jsl.utilities.jsldbsrc.tables.BatchStat;
import jsl.utilities.jsldbsrc.tables.BatchStatView;
import jsl.utilities.jsldbsrc.tables.ModelElement;
import jsl.utilities.jsldbsrc.tables.SimulationRun;
import jsl.utilities.jsldbsrc.tables.WithinRepCounterStat;
import jsl.utilities.jsldbsrc.tables.WithinRepCounterView;
import jsl.utilities.jsldbsrc.tables.WithinRepResponseView;
import jsl.utilities.jsldbsrc.tables.WithinRepStat;


/**
 * Convenience access to all tables in JSL_DB
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>JSL_DB.ACROSS_REP_STAT</code>.
     */
    public static final AcrossRepStat ACROSS_REP_STAT = jsl.utilities.jsldbsrc.tables.AcrossRepStat.ACROSS_REP_STAT;

    /**
     * The table <code>JSL_DB.ACROSS_REP_VIEW</code>.
     */
    public static final AcrossRepView ACROSS_REP_VIEW = jsl.utilities.jsldbsrc.tables.AcrossRepView.ACROSS_REP_VIEW;

    /**
     * The table <code>JSL_DB.BATCH_STAT</code>.
     */
    public static final BatchStat BATCH_STAT = jsl.utilities.jsldbsrc.tables.BatchStat.BATCH_STAT;

    /**
     * The table <code>JSL_DB.BATCH_STAT_VIEW</code>.
     */
    public static final BatchStatView BATCH_STAT_VIEW = jsl.utilities.jsldbsrc.tables.BatchStatView.BATCH_STAT_VIEW;

    /**
     * The table <code>JSL_DB.MODEL_ELEMENT</code>.
     */
    public static final ModelElement MODEL_ELEMENT = jsl.utilities.jsldbsrc.tables.ModelElement.MODEL_ELEMENT;

    /**
     * The table <code>JSL_DB.SIMULATION_RUN</code>.
     */
    public static final SimulationRun SIMULATION_RUN = jsl.utilities.jsldbsrc.tables.SimulationRun.SIMULATION_RUN;

    /**
     * The table <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code>.
     */
    public static final WithinRepCounterStat WITHIN_REP_COUNTER_STAT = jsl.utilities.jsldbsrc.tables.WithinRepCounterStat.WITHIN_REP_COUNTER_STAT;

    /**
     * The table <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code>.
     */
    public static final WithinRepCounterView WITHIN_REP_COUNTER_VIEW = jsl.utilities.jsldbsrc.tables.WithinRepCounterView.WITHIN_REP_COUNTER_VIEW;

    /**
     * The table <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW</code>.
     */
    public static final WithinRepResponseView WITHIN_REP_RESPONSE_VIEW = jsl.utilities.jsldbsrc.tables.WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW;

    /**
     * The table <code>JSL_DB.WITHIN_REP_STAT</code>.
     */
    public static final WithinRepStat WITHIN_REP_STAT = jsl.utilities.jsldbsrc.tables.WithinRepStat.WITHIN_REP_STAT;
}
